apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_HOST: tfdevopspg98765.postgres.database.azure.com
  POSTGRES_PORT: "5432"
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: StrongPass123!
  POSTGRES_SSLMODE: require

